version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edtech-api
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgrespasswd@db:5432/edtechapp
      - JWT_SECRET=${JWT_SECRET:-019594f4-3ccc-73fb-a0b2-3f5bd920153e}
    volumes:
      - ./logs:/app/logs
    networks:
      - edtech-network
    command: >
      sh -c "npx prisma migrate deploy && npm start"

  db:
    image: postgres:16-alpine
    container_name: edtech-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespasswd
      - POSTGRES_DB=edtechapp
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - edtech-network

volumes:
  postgres_data:

networks:
  edtech-network:
    driver: bridge
